// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'metrics.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Metrics _$MetricsFromJson(Map<String, dynamic> json) => Metrics(
      (json['id'] as num?)?.toInt(),
      (json['impressions'] as num?)?.toDouble(),
      (json['conversions'] as num?)?.toDouble(),
      (json['clicks'] as num?)?.toDouble(),
      (json['cost'] as num?)?.toDouble(),
      (json['topImpressionShare'] as num?)?.toDouble(),
      (json['budgetLostTopImpressionShare'] as num?)?.toDouble(),
      (json['budgetLostImpressionShare'] as num?)?.toDouble(),
      (json['exactMatchImpressionShare'] as num?)?.toDouble(),
      (json['impressionShare'] as num?)?.toDouble(),
      (json['rankLostTopImpressionShare'] as num?)?.toDouble(),
      (json['rankLostImpressionShare'] as num?)?.toDouble(),
      (json['overallTopImpressionShare'] as num?)?.toDouble(),
      (json['valuePerConversion'] as num?)?.toDouble(),
      (json['conversionRate'] as num?)?.toDouble(),
      (json['videoViews'] as num?)?.toDouble(),
      (json['viewThroughConversions'] as num?)?.toDouble(),
      (json['interactionConversionRate'] as num?)?.toDouble(),
      (json['conversionValue'] as num?)?.toDouble(),
      (json['costPerConversion'] as num?)?.toDouble(),
      (json['crossDeviceConversions'] as num?)?.toDouble(),
      (json['ctr'] as num?)?.toDouble(),
      (json['attributedConversions'] as num?)?.toDouble(),
      (json['attributedConversionValue'] as num?)?.toDouble(),
      (json['attributedConversionValuePerCost'] as num?)?.toDouble(),
      (json['engagements'] as num?)?.toDouble(),
      (json['measurableImpressions'] as num?)?.toDouble(),
      (json['measurabilityRate'] as num?)?.toDouble(),
      (json['measurableCost'] as num?)?.toDouble(),
      (json['measurableImpressionShare'] as num?)?.toDouble(),
      (json['allConversionsValue'] as num?)?.toDouble(),
      (json['averageCost'] as num?)?.toDouble(),
      (json['averageCpc'] as num?)?.toDouble(),
      (json['averageCpm'] as num?)?.toDouble(),
      (json['averagePageViews'] as num?)?.toDouble(),
      (json['averageTimeOnSite'] as num?)?.toDouble(),
      (json['bounceRate'] as num?)?.toDouble(),
      (json['forwards'] as num?)?.toDouble(),
      (json['saves'] as num?)?.toDouble(),
      (json['secondaryClicks'] as num?)?.toDouble(),
      (json['interactionRate'] as num?)?.toDouble(),
      (json['interactions'] as num?)?.toDouble(),
      (json['invalidClickRate'] as num?)?.toDouble(),
      (json['invalidClicks'] as num?)?.toDouble(),
      (json['newVisitorRate'] as num?)?.toDouble(),
      (json['phoneCalls'] as num?)?.toDouble(),
      (json['phoneImpressions'] as num?)?.toDouble(),
      (json['targetCpa'] as num?)?.toDouble(),
      (json['newCustomerLifetimeValue'] as num?)?.toDouble(),
      (json['allNewCustomerLifetimeValue'] as num?)?.toDouble(),
      (json['orders'] as num?)?.toDouble(),
      (json['averageOrderValue'] as num?)?.toDouble(),
      (json['costOfGoodsSold'] as num?)?.toDouble(),
      (json['grossProfit'] as num?)?.toDouble(),
      (json['revenue'] as num?)?.toDouble(),
      (json['unitsSold'] as num?)?.toDouble(),
      (json['crossSellCostOfGoodsSold'] as num?)?.toDouble(),
      (json['crossSellGrossProfit'] as num?)?.toDouble(),
      (json['leadCostOfGoodsSold'] as num?)?.toDouble(),
      (json['crossDeviceConversionValue'] as num?)?.toDouble(),
      json['displayName'] as String?,
    );

Map<String, dynamic> _$MetricsToJson(Metrics instance) => <String, dynamic>{
      'id': instance.id,
      'impressions': instance.impressions,
      'conversions': instance.conversions,
      'clicks': instance.clicks,
      'cost': instance.cost,
      'topImpressionShare': instance.topImpressionShare,
      'budgetLostTopImpressionShare': instance.budgetLostTopImpressionShare,
      'budgetLostImpressionShare': instance.budgetLostImpressionShare,
      'exactMatchImpressionShare': instance.exactMatchImpressionShare,
      'impressionShare': instance.impressionShare,
      'rankLostTopImpressionShare': instance.rankLostTopImpressionShare,
      'rankLostImpressionShare': instance.rankLostImpressionShare,
      'overallTopImpressionShare': instance.overallTopImpressionShare,
      'valuePerConversion': instance.valuePerConversion,
      'conversionRate': instance.conversionRate,
      'videoViews': instance.videoViews,
      'viewThroughConversions': instance.viewThroughConversions,
      'interactionConversionRate': instance.interactionConversionRate,
      'conversionValue': instance.conversionValue,
      'costPerConversion': instance.costPerConversion,
      'crossDeviceConversions': instance.crossDeviceConversions,
      'ctr': instance.ctr,
      'attributedConversions': instance.attributedConversions,
      'attributedConversionValue': instance.attributedConversionValue,
      'attributedConversionValuePerCost':
          instance.attributedConversionValuePerCost,
      'engagements': instance.engagements,
      'measurableImpressions': instance.measurableImpressions,
      'measurabilityRate': instance.measurabilityRate,
      'measurableCost': instance.measurableCost,
      'measurableImpressionShare': instance.measurableImpressionShare,
      'allConversionsValue': instance.allConversionsValue,
      'averageCost': instance.averageCost,
      'averageCpc': instance.averageCpc,
      'averageCpm': instance.averageCpm,
      'averagePageViews': instance.averagePageViews,
      'averageTimeOnSite': instance.averageTimeOnSite,
      'bounceRate': instance.bounceRate,
      'forwards': instance.forwards,
      'saves': instance.saves,
      'secondaryClicks': instance.secondaryClicks,
      'interactionRate': instance.interactionRate,
      'interactions': instance.interactions,
      'invalidClickRate': instance.invalidClickRate,
      'invalidClicks': instance.invalidClicks,
      'newVisitorRate': instance.newVisitorRate,
      'phoneCalls': instance.phoneCalls,
      'phoneImpressions': instance.phoneImpressions,
      'targetCpa': instance.targetCpa,
      'newCustomerLifetimeValue': instance.newCustomerLifetimeValue,
      'allNewCustomerLifetimeValue': instance.allNewCustomerLifetimeValue,
      'orders': instance.orders,
      'averageOrderValue': instance.averageOrderValue,
      'costOfGoodsSold': instance.costOfGoodsSold,
      'grossProfit': instance.grossProfit,
      'revenue': instance.revenue,
      'unitsSold': instance.unitsSold,
      'crossSellCostOfGoodsSold': instance.crossSellCostOfGoodsSold,
      'crossSellGrossProfit': instance.crossSellGrossProfit,
      'leadCostOfGoodsSold': instance.leadCostOfGoodsSold,
      'crossDeviceConversionValue': instance.crossDeviceConversionValue,
      'displayName': instance.displayName,
    };
